name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust Toolchain Components
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt

    - uses: Swatinem/rust-cache@v3

    - name: Clippy
      run: cargo clippy --all --all-targets -- -A clippy::cast_lossless -A clippy::cast_possible_truncation -A clippy::cast_possible_wrap -A clippy::cast_sign_loss -A clippy::useless_conversion

    - name: Format
      run: cargo fmt --all -- --check

  test:
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust Toolchain Components
      uses: dtolnay/rust-toolchain@stable

    - uses: Swatinem/rust-cache@v3

    - name: Test
      run: cargo test --all
